# Site settings

# Title of the Webpage (e.g. group name)
title: "VCP Stamm Martin Luther"
# Short description of the group (single line)
description: "Pfadfinden in Eisenach."
# Name of the group
group_name: VCP Stamm Martin Luther
# Address of the group
group_address: >
  Am Kirchweg 3<br/>
  12345 Eisenach
# Phone number of the group
group_phone: 0123 / 456 78 90
# Emailadress of the group
group_email: kontakt@test-stamm.de
# Name of the Webmaster
name: 'Walter Webmaster'
# Emailadress of the Webmaster
email: info@johannes-engelke.de

# URL of the webpage
url: "http://vcp-de.github.io/" # the base hostname & protocol for your site

# Images

#blog logo
logo: "/assets/images/VCP-Zeichen-RGB-128px.png"
# blog cover
cover: "/assets/images/VCP_Plakate_2012_3_lowres.jpg"

# Build settings
markdown: redcarpet
highlighter: pygments

collections:
  team:

  groups:
    output: true

baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/VCP_de
    desc: Folge mir auf twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	facebook
    url:	https://www.facebook.com/groups/vcp.oearbeit/?fref=ts
    desc: Folge mir auf facebook
    share_url: //www.facebook.com/sharer/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

#  - icon:	github
#    url:	https://github.com/dirkfabisch
#    desc:	Fork me on github
#    share_url:
#    share_title:
#    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
